[TakeImage]
;RawImagesLocation = /log/source
;RawImagesRetention = 15
WaitBeforeTakingPicture = 2
CamGainceiling = x8
CamQuality = 10
CamBrightness = 0
CamContrast = 0
CamSaturation = -1
CamSharpness = 0
CamAutoSharpness = false
CamSpecialEffect = no_effect
CamWbMode = auto
CamAwb = true
CamAwbGain = true
CamAec = true
CamAec2 = true
CamAeLevel = 2
CamAecValue = 600
CamAgc = true
CamAgcGain = 8
CamBpc = true
CamWpc = true
CamRawGma = true
CamLenc = true
CamHmirror = false
CamVflip = false
CamDcw = true
CamDenoise = 0
CamZoom = false
CamZoomOffsetX = 0
CamZoomOffsetY = 0
CamZoomSize = 0
LEDIntensity = 10
Demo = false

[Alignment]
InitialRotate = -148.0
SearchFieldX = 20
SearchFieldY = 20
AlignmentAlgo = default
/config/ref0.jpg 329 210
/config/ref1.jpg 388 281

[Digits]
Model = /config/dig-class11_1910_s2_q.tflite
CNNGoodThreshold = 0.5
;ROIImagesLocation = /log/digit
;ROIImagesRetention = 3
water_m.dig1 240 249 22 40 false
water_m.dig2 264 249 22 40 false
water_m.dig3 281 249 22 40 false
water_m.dig4 303 249 22 40 0
water_m.dig5 325 249 22 40 0
water_m.dig6 347 249 22 40 0
water_m.dig7 365 249 22 40 0

;[Analog]
Model = /config/ana-cont_1500_s2_q.tflite
;ROIImagesLocation = /log/analog
;ROIImagesRetention = 3
water_m.ana1 432 230 92 92 false
water_m.ana2 379 332 92 92 false
water_m.ana3 283 374 92 92 false
water_m.ana4 155 328 92 92 false

[PostProcessing]
water_m.DecimalShift = -3
;water_m.AnalogToDigitTransitionStart = 
water_m.ChangeRateThreshold = 1
PreValueUse = true
PreValueAgeStartup = 720
water_m.AllowNegativeRates = false
;water_m.MaxRateValue = 0.05
water_m.MaxRateType = RateChange
water_m.ExtendedResolution = false
water_m.IgnoreLeadingNaN = false
ErrorMessage = true
water_m.CheckDigitIncreaseConsistency = false

[MQTT]
Uri = mqtt://192.168.100.3:1883
MainTopic = watermeter
ClientID = watermeter
user = CHANGENYUSERNAME
password = CHANGEMESEMOUR
RetainMessages = false
;DomoticzTopicIn = domoticz/in
;water_m.DomoticzIDX = 0
HomeassistantDiscovery = true
MeterType = water_m3
;CACert = /config/certs/RootCA.pem
;ClientCert = /config/certs/client.pem.crt
;ClientKey = /config/certs/client.pem.key
;ValidateServerCert = true

;[InfluxDB]
;Uri = undefined
;Database = undefined
;user = undefined
;password = undefined
;water_m.Measurement = undefined
;water_m.Field = undefined

;[InfluxDBv2]
;Uri = undefined
;Bucket = undefined
;Org = undefined
;Token = undefined
;water_m.Measurement = undefined
;water_m.Field = undefined

;[Webhook]
;Uri = undefined
;ApiKey = undefined
;UploadImg = 0

;[GPIO]
;IO0 = input disabled 10 false false 
;IO1 = input disabled 10 false false 
;IO3 = input disabled 10 false false 
;IO4 = built-in-led disabled 10 false false 
;IO12 = input-pullup disabled 10 false false 
;IO13 = input-pullup disabled 10 false false 
LEDType = WS2812
LEDNumbers = 2
LEDColor = 150 150 150

[AutoTimer]
Interval = 1

[DataLogging]
DataLogActive = false
DataFilesRetention = 3

[Debug]
LogLevel = 1
LogfilesRetention = 3

[System]
Tooltip = true
TimeZone = EET-2EEST,M3.5.0/3,M10.5.0/4
;TimeServer = pool.ntp.org
;Hostname = undefined
RSSIThreshold = -75
CPUFrequency = 160
SetupMode = false
